import type { GenerateResponse, Recommendation, TasteProfile } from "./types";

const MOCK_PROFILE: TasteProfile = {
  headline: "Anxious intensity with a soft spot for nostalgia",
  summary:
    "You're drawn to art that sits in uncomfortable emotional rooms — the kind that makes you hold your breath — but you come back to work that remembers being young and unsure. You're skeptical of sentimentality but you'll forgive a lot for a voice that feels honest.",
  dimensions: [
    { label: "Anxious intensity", strength: 0.9, description: "You respond to art that keeps tension humming under the surface." },
    { label: "Emotional honesty", strength: 0.85, description: "You'd rather something land awkwardly than land safely." },
    { label: "Craft-forward", strength: 0.75, description: "You notice when something is made with care and get out of the way of something that isn't." },
    { label: "Nostalgic warmth", strength: 0.6, description: "A contrasting pull toward work that remembers the texture of growing up." },
    { label: "Low tolerance for sentimentality", strength: 0.55, description: "You'll turn off the thing that's trying too hard." },
  ],
  loves: ["tight pacing", "unreliable narrators", "music that sounds like weather", "food that tastes like a place", "places with a real hum"],
  avoids: ["sprawling runtimes", "characters you can't feel any friction with", "food that's only pretty", "places designed for photos"],
  sourceText: "demo",
};

const MOCK_RECS: Recommendation[] = [
  {
    id: "r1",
    category: "film",
    title: "Good Time",
    creator: "Safdie Brothers",
    year: 2017,
    hook: "A propulsive NYC night that never lets you exhale.",
    whyYou: "You said you want anxiety you can't look away from — this is 100 minutes of it, and the soundtrack does half the work.",
    tags: ["Anxious intensity", "Craft-forward"],
    confidence: 0.92,
  },
  {
    id: "r2",
    category: "book",
    title: "A Little Life",
    creator: "Hanya Yanagihara",
    year: 2015,
    hook: "A novel that earns every tear it draws.",
    whyYou: "You forgive a lot for a voice that feels honest. This one takes you up on that offer.",
    tags: ["Emotional honesty", "Anxious intensity"],
    confidence: 0.84,
  },
  {
    id: "r3",
    category: "music",
    title: "For Emma, Forever Ago",
    creator: "Bon Iver",
    year: 2008,
    hook: "A cabin, a breakup, and a voice that sounds like weather.",
    whyYou: "You like music that sounds like a place. This one is a cold one.",
    tags: ["Nostalgic warmth", "Emotional honesty"],
    confidence: 0.88,
  },
  {
    id: "r4",
    category: "food",
    title: "Hainanese chicken rice",
    hook: "A dish that refuses to show off.",
    whyYou: "You said you hate food that's only pretty. This is the opposite: it's only good.",
    tags: ["Craft-forward"],
    confidence: 0.79,
  },
  {
    id: "r5",
    category: "place",
    title: "Tokyo's Golden Gai",
    hook: "Six alleys of six-seat bars, each with its own logic.",
    whyYou: "You said places designed for photos leave you cold. Nothing about this asks to be photographed.",
    tags: ["Craft-forward", "Emotional honesty"],
    confidence: 0.82,
  },
  {
    id: "r6",
    category: "show",
    title: "The Bear",
    creator: "Christopher Storer",
    year: 2022,
    hook: "Kitchen chaos as grief language.",
    whyYou: "Anxiety, craft, a low tolerance for people who don't care — it's all here in 30-minute episodes.",
    tags: ["Anxious intensity", "Craft-forward", "Emotional honesty"],
    confidence: 0.95,
  },
  {
    id: "r7",
    category: "book",
    title: "Stoner",
    creator: "John Williams",
    year: 1965,
    hook: "A quiet American life that ambushes you.",
    whyYou: "It's the version of nostalgia you actually like — unadorned, honest about what was lost.",
    tags: ["Nostalgic warmth", "Emotional honesty"],
    confidence: 0.8,
  },
  {
    id: "r8",
    category: "music",
    title: "A Seat at the Table",
    creator: "Solange",
    year: 2016,
    hook: "A record built like a room you can sit in.",
    whyYou: "Craft that doesn't announce itself — the kind you respect on a second listen.",
    tags: ["Craft-forward"],
    confidence: 0.76,
  },
  {
    id: "r9",
    category: "film",
    title: "Paris, Texas",
    creator: "Wim Wenders",
    year: 1984,
    hook: "A man walks out of the desert and back toward a family.",
    whyYou: "The version of slow you'll sit still for — every frame earns its minutes.",
    tags: ["Craft-forward", "Nostalgic warmth"],
    confidence: 0.78,
  },
  {
    id: "r10",
    category: "podcast",
    title: "Heavyweight",
    creator: "Jonathan Goldstein",
    year: 2016,
    hook: "People revisit the moment their life bent sideways.",
    whyYou: "Nostalgia handled with a scalpel, not a ladle.",
    tags: ["Nostalgic warmth", "Emotional honesty"],
    confidence: 0.81,
  },
  {
    id: "r11",
    category: "place",
    title: "Marfa, Texas",
    hook: "Desert minimalism built by a cranky sculptor.",
    whyYou: "A place with a real hum and no interest in your camera.",
    tags: ["Craft-forward"],
    confidence: 0.72,
  },
];

export function mockResponse(sourceText: string): GenerateResponse {
  return {
    profile: { ...MOCK_PROFILE, sourceText },
    recs: {
      hero: MOCK_RECS[0],
      browse: MOCK_RECS.slice(1),
      generatedAt: new Date().toISOString(),
    },
    demo: true,
  };
}
